// Curated sentences from Project Gutenberg texts
// Focus on voice, speech, personal growth, and general wisdom

export const SENTENCES = [
  // Voice and Speech themed
  "The sound of her voice was like music to his ears.",
  "He spoke with a clear and confident tone.",
  "Her words carried the weight of experience.",
  "The voice that answered was gentle and kind.",
  "She found her voice in the most unexpected moment.",
  "His voice rang out across the valley.",
  "The power of speech is the power to inspire.",
  "Words spoken with conviction can move mountains.",
  "Her voice trembled with emotion.",
  "He cleared his throat and began to speak.",
  "The echo of her voice lingered in the air.",
  "A soft voice can carry great strength.",
  "She spoke with the wisdom of ages.",
  "His voice grew stronger with each word.",
  "The silence was broken by a single voice.",
  
  // Personal Growth and Self-Improvement
  "Every day is a chance to become better.",
  "She knew that change begins from within.",
  "The journey of self-discovery never truly ends.",
  "He learned to trust his own judgment.",
  "Growth comes from facing our fears.",
  "She embraced the challenge with open arms.",
  "The path to wisdom is paved with experience.",
  "He chose courage over comfort.",
  "Progress is made one step at a time.",
  "She discovered strength she never knew she had.",
  "The greatest teacher is experience itself.",
  "He learned to see failure as a stepping stone.",
  "Change is the only constant in life.",
  "She transformed her weakness into strength.",
  "The power to change lies within us all.",
  "He found peace in accepting himself.",
  "Every moment offers a chance to begin again.",
  "She learned that patience is a virtue worth cultivating.",
  "The mind is capable of remarkable things.",
  "He discovered that true strength comes from within.",
  
  // General Wisdom and Life Lessons
  "The sun rose over the distant mountains.",
  "Time flows like a river, steady and sure.",
  "The old tree stood strong against the wind.",
  "She watched the stars appear one by one.",
  "The morning brought fresh hope and promise.",
  "He walked through fields of golden wheat.",
  "The ocean stretched endlessly before them.",
  "Nature teaches us lessons we often overlook.",
  "The seasons change but beauty remains.",
  "She felt the warmth of the afternoon sun.",
  "The moon cast silver light upon the water.",
  "He found solace in the quiet of the forest.",
  "The wind whispered secrets through the trees.",
  "She admired the simplicity of the countryside.",
  "The garden bloomed with vibrant colors.",
  "He listened to the song of the morning birds.",
  "The rain fell gently on the roof.",
  "She treasured the peace of the evening hour.",
  "The flowers swayed in the gentle breeze.",
  "He marveled at the beauty of creation.",
  
  // Relationships and Human Connection
  "Friendship is a treasure beyond measure.",
  "She valued honesty above all else.",
  "Trust is built slowly and lost quickly.",
  "He learned the importance of kindness.",
  "Love grows stronger through shared experiences.",
  "She showed compassion to all she met.",
  "Understanding bridges the gap between hearts.",
  "He offered a helping hand without hesitation.",
  "Gratitude opens doors to happiness.",
  "She cherished the bonds of family.",
  "True friends stand by you in difficult times.",
  "He learned to listen with an open heart.",
  "Respect is earned through consistent action.",
  "She treated everyone with equal dignity.",
  "Forgiveness frees the soul from burden.",
  
  // Action and Determination
  "She set her mind to the task at hand.",
  "He refused to give up despite the odds.",
  "Determination fuels the fire of achievement.",
  "She took the first step toward her goal.",
  "Action speaks louder than words alone.",
  "He pursued his dreams with unwavering focus.",
  "She faced each obstacle with renewed vigor.",
  "Perseverance is the key to success.",
  "He worked diligently toward his purpose.",
  "She proved that dedication yields results.",
  "The will to succeed overcomes many barriers.",
  "He moved forward with steadfast resolve.",
  "She turned her vision into reality.",
  "Effort and patience bring their own rewards.",
  "He demonstrated that hard work pays off.",
  
  // Thought and Reflection
  "She paused to consider her next move.",
  "Reflection brings clarity to confusion.",
  "He pondered the meaning of his experiences.",
  "The quiet mind sees what the busy mind misses.",
  "She valued moments of peaceful contemplation.",
  "Wisdom comes from thoughtful consideration.",
  "He learned to think before acting.",
  "The examined life is worth living.",
  "She questioned assumptions and sought truth.",
  "Understanding grows from careful observation.",
  "He found answers in moments of stillness.",
  "The mind needs rest as much as the body.",
  "She practiced mindfulness in daily life.",
  "Reflection transforms experience into wisdom.",
  "He discovered insights through introspection.",
  
  // Hope and Optimism
  "Tomorrow brings new opportunities.",
  "She held fast to hope in dark times.",
  "The future is full of possibilities.",
  "He believed in the power of positive thinking.",
  "Light always follows the darkest night.",
  "She saw the silver lining in every cloud.",
  "Hope is the anchor of the soul.",
  "He faced the future with optimism.",
  "The dawn of a new day brings fresh starts.",
  "She trusted that better days were ahead.",
  "Faith in tomorrow sustains us today.",
  "He chose to see the good in every situation.",
  "The human spirit is remarkably resilient.",
  "She found joy in simple pleasures.",
  "Hope springs eternal in the human heart.",
  
  // Learning and Knowledge
  "Every experience teaches us something valuable.",
  "She approached life as a constant student.",
  "Knowledge is gained through curiosity and effort.",
  "He read widely and learned continuously.",
  "The pursuit of learning enriches the mind.",
  "She asked questions and sought understanding.",
  "Ignorance is dispelled by the light of knowledge.",
  "He valued education in all its forms.",
  "The wise person never stops learning.",
  "She embraced new ideas with enthusiasm.",
  "Books open windows to other worlds.",
  "He learned from both success and failure.",
  "The mind expands with each new discovery.",
  "She studied with dedication and purpose.",
  "Knowledge empowers us to grow.",
  
  // Courage and Bravery
  "She summoned courage from deep within.",
  "Fear is conquered by facing it directly.",
  "He took a brave step into the unknown.",
  "Courage is not the absence of fear.",
  "She stood firm in her convictions.",
  "Bravery is found in everyday actions.",
  "He dared to be different from the crowd.",
  "She spoke up when others remained silent.",
  "Courage transforms the ordinary into extraordinary.",
  "He refused to let fear dictate his choices.",
  
  // Peace and Contentment
  "She found peace in accepting what cannot be changed.",
  "Contentment comes from within, not from without.",
  "He learned to be still and simply be.",
  "The peaceful heart knows true happiness.",
  "She cultivated inner calm through practice.",
  "Serenity is found in the present moment.",
  "He let go of worry and embraced peace.",
  "She discovered joy in ordinary moments.",
  "Peace begins with a smile and an open heart.",
  "He found balance between effort and rest.",
  
  // Additional variety
  "The clock struck twelve as midnight approached.",
  "She opened the door and stepped outside.",
  "The path wound through hills and valleys.",
  "He remembered lessons from long ago.",
  "The book lay open on the table.",
  "She smiled at the memory of that day.",
  "The bridge spanned the rushing river below.",
  "He gazed out the window at the world.",
  "The fire crackled warmly in the hearth.",
  "She felt grateful for all she had been given.",
];

